from huobi.model_proto.aggregatetrade import AggregateTrade

class AggregateTradeEvent:
    """
    The summary of trading in the market for the last 24 hours

    :member
        timestamp: The UNIX formatted timestamp generated by server in UTC.
        open: The opening price of last 24 hours.
        close: The last price of last 24 hours.
        amount: The aggregated trading volume in USDT.
        high: The high price of last 24 hours.
        low: The low price of last 24 hours.
        count: The number of completed trades.
        volume: The trading volume in base currency of last 24 hours.
    """

    def __init__(self):
        self.symbol = ""
        self.timestamp = 0
        self.data = AggregateTrade()
